### ISSUE TITLE
Missing files while predictions

### ISSUE THREAD

**Issue by brijhub** [i-pan/kaggle-rsna18#1]
I downloaded trained model and everytme when I start running predict.sh bash, I get some missing files error.
![screenshot from 2018-11-28 10 58 53](https://user-images.githubusercontent.com/26489715/49131116-e7d55b80-f2fc-11e8-9c40-5edd0021d715.png)

Can you please provide steps for predicting single xray image?

**Comment by i-pan** [comment]
@brijhub Do the rest of the steps in `predict.sh` work properly? Can you show me the `ls` output in the top-level directory?

**Comment by brijhub** [comment]
Sure @i-pan 
Here is directory structure

![direcory_structure](https://user-images.githubusercontent.com/26489715/49493019-8115ec00-f880-11e8-973f-803252325570.png)

Downloaded trained model is inside models/ directory.
![prediction_error](https://user-images.githubusercontent.com/26489715/49493223-45c7ed00-f881-11e8-90a6-d1465d23956a.png)

Thanx for your time.

**Comment by i-pan** [comment]
@brijhub Make sure you have set up all the necessary requirements. It seems like you don't have `keras` installed.
